### ISSUE TITLE
Unable to add HDMI output

### ISSUE THREAD

**Issue by ghost** [ovenwerks/studio-controls#54]
When I upgraded to 2.1.64-beta (from Ubuntu Studio repo), I started to have problems with Jack and Pulse. I erased ~/.config/jack and ~/autojack and restarted my computer (because I was lazy) and it's now working again, but I can't add an HDMI output; when I do, the options are grayed out and I can't specify the number of output channels I need (only 2). Is it a bug, or is there a way to get back that functionality?
Update: I tried to fix the issue, in redraw_extra and xdev_changed, without success.
Update: I tried the convert-studio-controls command; of course there's no need to use it because I erased my previous settings, but studio-controls should have created a new set of valid settings. If it can help, my HDMI output is from a Nvidia GPU in a laptop.
Update: I downgraded to version 2.1.4, and similar problems occurs (I can't add a HDMI device as I used too); in Extra Devices tab, the Sample Rate dropdown menu for my HDMI device is empty.

**Comment by mrz80** [comment]
How'd you downgrade to 2.1.4?  I had everything working more or less perfectly, but as soon as 2.1.64 showed up, everything jack-related went haywire. Saved connections didn't reconnect, studio-controls could no longer reliably start or stop jackd, and MIDI was rendered completely nonfuctional no matter what combination of settings I tried. I ended up burning and reinstalling without the backports ppa, but that's lost me a lot of carla functionality/reliability. So, if I could install the backports ppa then backdate studio-controls to 2.1.4 that would be marvelous.

**Comment by ghost** [comment]
If you want to go back to version 2.1.4, first uninstall 2.1.64, and restart from scratch by erasing your `~/.config/jack/` and `~/.config/autojack/` directory. Then download the deb package for version 2.1.4 from this url:
`http://ppa.launchpad.net/ubuntustudio-ppa/backports/ubuntu/pool/main/s/studio-controls/studio-controls_2.1.4-0ubuntu1~ubuntu20.10.1~ppa1_all.deb`
Install it with `sudo dpkg -i`, etc...

**Comment by ghost** [comment]
In version 2.1.64 there's a conversion utility for the settings: /usr/bin/convert-studio-controls
So maybe it could solve your problem...

The problem I experience may not be caused directly by version 2.1.64... Since I started using the official Nvidia drivers, version 2.1.4 of Studio Controls does not work either to configure my HDMI sound output. I have a laptop specifically designed for running Linux, but with a special version of the Nvidia driver that as incompatible with the official CUDA drivers... Because PulseAudio works fine, I suspect there's something missing in Studio Controls (all versions) for my specific case, or that the official Nvidia drivers are not exposing the information that Studio Controls is expecting.

**Comment by mrz80** [comment]
I'll try going for the backports ppa again, and running the convert-studio-controls utility. If I get no joy there, I'll wipe the configs and pin the machine back on 2.1.4.  Thanks folks!

**Comment by eeickmeyer** [comment]
I'm a bit confused by this entire discussion. In Ubuntu, there are only 3 ways you could've obtained 2.1.64-beta, which, as you'll note, is a prerelease beta and should not be used in production environments: 

- By upgrading to Impish Indri (future 21.10, which is unsupported at this time)
- By adding the Studio Controls staging PPA (unsupported)
- By compiling it yourself.

2.1.64-beta does NOT exist in the Ubuntu Studio Backports repository, so why on earth are you running unsupported, prerelease software on production systems? This isn't ready by any stretch of the imagination for production.

The latest *supported* version is 2.1.4. Please do not run versions beyond that as they're all pre-release software.

**Comment by ghost** [comment]
Indeed, version 2.1.64-beta is included in `http://ppa.launchpad.net/ubuntustudio-ppa/backports/ubuntu/pool/main/s/studio-controls/`
That's why it showed on my system after an upgrade...
Could it be a mistake?

**Comment by eeickmeyer** [comment]
Yeah, that doesn't look right. I had accidentally uploaded but aborted the build, but it looks like the damage was done. I'll see what I can do to trick your system. You might, however, want to upgrade to 21.04 regardless since 20.10 has about 1 1/2 months left of life (support ends in July).

**Comment by eeickmeyer** [comment]
Ok, I just uploaded a new package which is really 2.1.4 disguised as 2.1.64, should hit the PPA in about an hour or so.

**Comment by ghost** [comment]
> Yeah, that doesn't look right. I had accidentally uploaded but aborted the build, but it looks like the damage was done. I'll see what I can do to trick your system. You might, however, want to upgrade to 21.04 regardless since 20.10 has about 1 1/2 months left of life (support ends in July).

I use 20.04LTS only. Will it work?

**Comment by mrz80** [comment]
> I'm a bit confused by this entire discussion. In Ubuntu, there are only 3 ways you could've obtained 2.1.64-beta, which, as you'll note, is a prerelease beta and should not be used in production environments:
> 
2.1.64 just appeared a bit ago after an apt update/dist-upgrade cycle. I certainly didn't go out of my way to get it. :D  It hit both my Ubuntu Studio boxes at the same time.

>     * By upgrading to Impish Indri (future 21.10, which is unsupported at this time)
> 
Nope, running 20.04LTS on both machines.

>     * By adding the Studio Controls staging PPA (unsupported)
> 
Never did that. Verified that the staging PPA was NOT configured on either machine.

>     * By compiling it yourself.
> 
I'm lazy. I haven't compiled anything myself  in ages. :D 
 
> 2.1.64-beta does NOT exist in the Ubuntu Studio Backports repository, so why on earth are you running unsupported, prerelease software on production systems? This isn't ready by any stretch of the imagination for production.
> 
I haven't a rational explanation for how it wound up on either one of my boxes. Weird.

> The latest _supported_ version is 2.1.4. Please do not run versions beyond that as they're all pre-release software.
>
That's what I *want* to run.

**Comment by marclava** [comment]
> Yeah, that doesn't look right. I had accidentally uploaded but aborted the build, but it looks like the damage was done. I'll see what I can do to trick your system. You might, however, want to upgrade to 21.04 regardless since 20.10 has about 1 1/2 months left of life (support ends in July).

I use 20.04LTS only. Will it work?

**Comment by eeickmeyer** [comment]
As I stated before, I uploaded it accidentally to the backports repository but for 20.10, and I find it strange that it added for 20.04. I'll look into it further.

**Comment by eeickmeyer** [comment]
Either way, uploaded 2.1.4 to the backports again for 20.04 to make sure the right version is there.

**Comment by ovenwerks** [comment]
First of all thank you for testing. If you are using HDMI as jack master, the number of outputs can not be changed. This is the way JACK works. If you are adding hdmi as an extra device, that should be able to work.

You have mentioned redraw_extra and xdev_changed, so I will assume you mean as an extra device. Because you rm ~/.config/autojack/ the first thing I would have checked (hide this device) should not be checked.

**Comment by mrz80** [comment]
> Either way, uploaded 2.1.4 to the backports again for 20.04 to make sure the right version is there.

Cool, thanks!  I use this computer for work, so I probably ought to wait 'til tonight to monkey with it.  I'll re-enable the backports ppa and give it a shot this evening.

**Comment by ghost** [comment]
@ovenwerks : I use my internal codec as the master, then I want to add the HDMI audio of my external monitor. It no longer work, even after going back to version 2.1.4. So I suspect that something is missing in the kernel drivers. I have to use the official evil proprietary Nvidia drivers, not the ones provided by the laptop company (that worked well for audio, but not with CUDA). My next laptop will be free of any Nvidia hardware, but until then I'll like to find a simple fix; it could be something hardwired in the python script of studio-controls... Thanks for your attention.

**Comment by mrz80** [comment]
> Either way, uploaded 2.1.4 to the backports again for 20.04 to make sure the right version is there.

Reactivated the backports-ppa, did an update, and everything is beautiful again. Thank you!  Sound and MIDI are behaving as they're supposed to, my USB audio interface is auto-detected when I turn it on, and heck, even the mic on my webcam is working, which it wasn't  before. Beautiful!

**Comment by ovenwerks** [comment]
This is fixed in 2.1.66

**Comment by ghost** [comment]
Hi, version 2.1.66 does not solve my (tm) problem. I noticed that the alsa-info script can collect info that studio-controls would need.
